name: Test CI/CD
on:
  push:        # Déclenche le workflow à chaque push
    branches:
      - experiment 
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run test premier CI/CD du projet
        run: echo "✅ CI/CD fonctionne correctement !"